---
# Conditional Playbook

- name: Conditional Playbook
  hosts: all
  become: yes

  tasks:
    - name: Install backup package
      yum:
        name: linuxacademy_backup_package
        state: present
      ignore_errors: true

    - name: Check for archive file
      command: ls /root/archive.tar
      register: check_result
      ignore_errors: true

    - name: Touch archive file
      file:
        path: /root/archive.tar
        state: touch
      when: check_result is failed
