---
- name: Playbook que demonstra o uso de variáveis em arquivos separados (e em lista)
  hosts: gerenciado
  become: yes
  gather_facts: no
  vars_files: ./user_info.yml
  tasks:
    - name: Create users
      user:
        name: "{{ item.name }}"
        state: present
        comment: "{{ item.comment }}"
        uid: "{{ item.id }}"
      loop: "{{ users }}"
        

