---
- name: Playbook demonstrativo - LVM
  become: yes
  hosts: gerenciado
  tasks:
    - name: Create VG
      lvg:
        pvs: /dev/nvme1n1p1,/dev/nvme2n1p1
        vg: vg_ansible
        state: present
    - name: Create LV
      lvol:
        vg: vg_ansible
        lv: lv_ansible
        size: 512m
        state: present
