---
- name: Playbook demonstrativo de uso de uma role
  hosts: gerenciado
  become: yes
  roles:
    - apache
 
# AS LINHAS À SEGUIR SOBRESCREVERIAM A VARIÁVEL DEFINIDA NA ROLE
# vars:
#   apache_http_port: 80
