---
- name: Playbook demonstrativo do módulo systemd
  hosts: gerenciado
  become: yes
  tasks:
    - name: Inicia e ativa na inicialização o serviço httpd
      systemd:
        name: httpd
        state: started
        enabled: yes
    - name: Inicia e ativa na inicialização o serviço firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes
