---
- name: Playbook demonstrativo do módulo unarchive
  become: yes
  hosts: gerenciado
  tasks:
    - name: unpack multiFile.tgz
      unarchive:
        src: ~cloud_user/unarchive/multi/multiFile.tgz
        dest: /home/cloud_user/unarchive/multi
        remote_src: yes

    - name: unpack globExclude.tgz
      unarchive:
        src: ~cloud_user/unarchive/glob/globExclude.tgz
        dest: /home/cloud_user/unarchive/glob
        remote_src: yes

    - name: unpack dir.tgz
      unarchive:
        src:  /home/cloud_user/unarchive/dirExample/dir.tgz
        dest:  /home/cloud_user/unarchive/dirExample
        remote_src: yes
